name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository se code fetch karna
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Files ko Ubuntu server par copy karna (Small letters me fix kiya hai yahan)
      - name: Deploy to EC2 via SSH rsync
        uses: easingthemes/ssh-deploy@main
        with:
          ssh_private_key: ${{ secrets.EC2_SSH_KEY }}
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USERNAME }}
          target: /var/www/html/
          args: "-rlgoDzvO --delete"

      # 3. Nginx Server ko automatically reload karna taaki naye changes dikhein
      - name: Reload Nginx Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl reload nginx